import http from 'node:http';import {readFile,mkdir,readdir} from 'node:fs/promises';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {progressAPI} from '../server/api.js';
await mkdir('.sites-runtime',{recursive:true});const database=new DatabaseSync('.sites-runtime/progress.sqlite');
for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort()){try{database.exec(await readFile(path.join('drizzle',name),'utf8'));}catch(e){if(!e.message.includes('already exists'))throw e;}}
const binding={prepare(sql){let values=[];return{bind(...args){values=args;return this;},async all(){return{results:database.prepare(sql).all(...values)};},async first(){return database.prepare(sql).get(...values)??null;},run(){return database.prepare(sql).run(...values);}};},async batch(items){database.exec('BEGIN');try{const results=items.map(item=>item.run());database.exec('COMMIT');return results;}catch(e){database.exec('ROLLBACK');throw e;}}};
const ids=new Set(Array.from({length:90},(_,i)=>'m'+String(i+1).padStart(2,'0')));
const files=new Set(['index.html','styles.css','worlds.css','robot.css','retro.css','phaser-world.css','assets/fonts/pixelify-sans.ttf','assets/fonts/OFL.txt','assets/PHASER-LICENSE.txt','engine.js','lessons.js','export.js','worlds.js','phaser-world.js','phaser.js','journey.js','app.js','assets/atlas-crt.png','assets/atlas-directions.png']);
for(const name of await readdir('web/assets/maps'))if(/^\d{2}-[a-z]+\.webp$/.test(name))files.add('assets/maps/'+name);
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:4173');if(url.pathname==='/api/progress'){const chunks=[];for await(const chunk of req)chunks.push(chunk);const headers=new Headers(req.headers);headers.set('oai-authenticated-user-id','local-development');const request=new Request(url,{method:req.method,headers,...(req.method==='POST'?{body:Buffer.concat(chunks)}:{})});const result=await progressAPI(request,{DB:binding},ids);res.writeHead(result.status,Object.fromEntries(result.headers));res.end(await result.text());return;}const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!files.has(name)){res.writeHead(404);res.end();return;}const data=name==='phaser.js'?await readFile('node_modules/phaser/dist/phaser.min.js'):await readFile(path.join('web',name));res.writeHead(200,{'content-type':name.endsWith('.ttf')?'font/ttf':name.endsWith('.txt')?'text/plain; charset=utf-8':name.endsWith('.webp')?'image/webp':name.endsWith('.png')?'image/png':name.endsWith('.css')?'text/css; charset=utf-8':name.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8','cache-control':'no-store'});res.end(data);}catch(e){console.error(e);res.writeHead(500);res.end('Local preview error');}});
server.listen(4173,'127.0.0.1',()=>console.log('Local: http://127.0.0.1:4173'));process.on('SIGINT',()=>server.close(()=>{database.close();process.exit(0);}));
