'use strict';
(() => {
const $=id=>document.getElementById(id),{levels,chapters,grade}=JavaCourse;
const names={predict:'Leer y predecir',order:'Ordenar instrucciones',fix:'Encontrar y corregir',write:'Programar',project:'Proyecto'};
const completed=new Set(),drafts=new Map(),arrangements=new Map(),predictions=new Map();
let current=levels.find(m=>m.id===location.hash.slice(1))??levels[(Math.min(9,Math.max(1,Number(location.hash.match(/^#map-(\d+)$/)?.[1])||1))-1)*10],result=null,cursor=-1,timer=null,hintCount=0,touched=false;
let saveTimer=null,saving=false,revision=0,savedRevision=0;

function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function stop(){if(timer)clearInterval(timer);timer=null;$('pause-button').hidden=true;$('run-button').textContent=result&&cursor>=0?'Continuar':'Ejecutar';}
function chunks(){if(!arrangements.has(current.id))arrangements.set(current.id,JavaCourse.orderStart(current).map((text,i)=>({text,key:i})));return arrangements.get(current.id);}
function source(){return current.mode==='predict'?current.code:current.mode==='order'?chunks().map(c=>c.text).join('\n'):$('code-editor').value;}
function highlight(code){const span=node('span');const regex=/(\/\/.*|"(?:\\.|[^"\\])*"|\b(?:class|interface|extends|implements|private|public|static|new|this|super|int|double|boolean|String|void|return|if|else|for|while|break|continue|true|false|null)\b|\b\d+(?:\.\d+)?\b|\b[A-Za-z_]\w*(?=\s*\())/g;let from=0;for(const match of code.matchAll(regex)){span.append(document.createTextNode(code.slice(from,match.index)));const token=match[0];span.append(node('span',token,token.startsWith('//')?'tok-comment':token.startsWith('"')?'tok-string':/^\d/.test(token)?'tok-number':code.slice(match.index+token.length).match(/^\s*\(/)?'tok-method':'tok-keyword'));from=match.index+token.length;}span.append(document.createTextNode(code.slice(from)));return span;}
function showCode(text,line=0){$('code-display').replaceChildren();text.split('\n').forEach((text,i)=>{const row=node('div',undefined,'code-line'+(i+1===line?' active':''));row.append(node('span',String(i+1),'line-number'));const code=node('code');code.append(highlight(text));row.append(code);$('code-display').append(row);});if(line){const active=$('code-display').querySelector('.active');if(active)$('code-display').scrollTop=Math.max(0,active.offsetTop-$('code-display').offsetTop-100);}}
function editing(){const editable=['fix','write','project'].includes(current.mode);$('code-editor').hidden=!editable||!!result;$('parsons').hidden=current.mode!=='order'||!!result;$('code-display').hidden=(editable&&!result)||(current.mode==='order'&&!result);$('restore-code').hidden=current.mode==='predict';if(current.mode==='order'&&!result)renderParsons();if(current.mode==='predict'||result)showCode(result?.source??source(),result&&cursor>=0?result.trace[cursor]?.line:0);}
function renderParsons(){const list=chunks();$('parsons').replaceChildren();list.forEach((chunk,i)=>{const row=node('div',undefined,'parsons-row'),buttons=node('div',undefined,'parsons-buttons');for(const [symbol,direction,label] of [['↑',-1,'Subir'],['↓',1,'Bajar']]){const button=node('button',symbol);button.type='button';button.setAttribute('aria-label',`${label} bloque ${i+1}`);button.disabled=i+direction<0||i+direction>=list.length;button.addEventListener('click',()=>{[list[i],list[i+direction]]=[list[i+direction],list[i]];renderParsons();$('parsons').children[i+direction].querySelector(`[aria-label^="${label}"]`)?.focus();});buttons.append(button);}row.append(node('code',chunk.text),buttons);$('parsons').append(row);});}
function renderRoute(){AtlasAdventure.route(current,completed);}
function renderState(state,snap=false){
 if(!state)return;
 AtlasAdventure.world(state,snap);
 $('object-state').replaceChildren();for(const object of state.objects){const card=node('div',undefined,'object-card');card.append(node('strong',`${object.robot?.name??object.cls} · #${object.id}`));if(object.robot){const r=object.robot;card.append(node('span',`(${r.x}, ${r.y}) · energía ${r.energy} · carga ${r.cargo} · entregas ${r.delivered}`));}for(const [name,v] of Object.entries(object.fields))card.append(node('div',`${name}: ${v.text}`));if(object.items)card.append(node('span','['+object.items.join(', ')+']'));$('object-state').append(card);}
 $('variable-state').replaceChildren();for(const [name,v] of Object.entries(state.vars))$('variable-state').append(node('span',`${v.type} ${name} = ${v.text}`,'variable'));$('call-stack').textContent='Pila: '+state.stack.join(' → ');$('console-output').textContent=state.output.length?state.output.join('\n'):'Sin mensajes de consola.';$('output-count').textContent=`${state.output.length} mensajes`;
}
function reference(){const root=$('reference-content');root.replaceChildren(node('p',chapters[current.chapter].reference));const dl=node('dl');for(const [command,meaning] of [['robot.este() / oeste() / norte() / sur()','Mueve una casilla y consume 1 energía; no cambia la orientación.'],['avanzar() / girarDerecha() / girarIzquierda()','Avanza hacia donde mira. Los giros cambian orientación sin mover.'],['recoger() / dejar() / recargar()','Recoge una caja de la casilla, deja una de su carga o recarga a 20 en una estación.'],['getX() / getY() / getEnergia() / getCarga() / getEntregas()','Consultan el estado sin modificarlo. getNombre() devuelve String.'],['puedeAvanzar() / hayCaja()','Sensores boolean. puedeAvanzar() comprueba el frente y la energía.'],['System.out.println(valor)','Imprime un valor. Puedes abrir la consola bajo el mapa.']]){const dt=node('dt');dt.append(node('code',command));dl.append(dt,node('dd',meaning));}root.append(node('p','Vista didáctica: las instrucciones pertenecen a jugar(Robot robot). Las clases y los métodos auxiliares se muestran junto a ellas; al descargar Mision.java se colocan en su ubicación Java correspondiente y se incluye main().'),dl,node('p','Alcance: intérprete educativo del subconjunto usado aquí. No admite Java completo, bibliotecas externas, sobrecarga ni excepciones Java. Cada bucle tiene un límite de 160 vueltas y cada prueba de 1200 pasos.'));}
function select(m,manual=false,enter=manual){
 if(['fix','write','project'].includes(current.mode)&&$('code-editor').value)drafts.set(current.id,$('code-editor').value);
 stop();current=m;result=null;cursor=-1;hintCount=0;if(manual){touched=true;history.replaceState(null,'',enter?'#'+m.id:'#map-'+(m.chapter+1));queueSave();}
 $('chapter-label').textContent=`${String(m.chapter+1).padStart(2,'0')} · ${chapters[m.chapter].title.toUpperCase()} · MISIÓN ${m.number}/90`;$('mission-title').textContent=m.title;$('mode-label').textContent=names[m.mode];$('mission-description').textContent=m.description;$('mission-goal').textContent=m.goal;$('question').textContent=m.question;
 $('task-title').textContent=m.mode==='predict'?'Antes de ejecutar':m.mode==='order'?'Construye la secuencia':'Tu turno de resolver';$('editor-note').textContent=m.mode==='predict'?'Lee primero. Haz una predicción.':m.mode==='order'?'Ordena los bloques con ↑ y ↓.':'Edita el programa. Las pistas te ayudan a razonar.';
 $('editor-context').textContent=m.chapter>=5?'Clases + jugar()':m.chapter===4?'Métodos + jugar()':'Dentro de jugar()';$('code-editor').value=drafts.get(m.id)??m.code;$('answers').replaceChildren();$('answers').hidden=m.mode!=='predict';$('answers').disabled=false;m.choices.forEach((choice,i)=>{const label=node('label',undefined,'answer'),input=node('input');input.type='radio';input.name='prediction';input.value=String(i);input.checked=predictions.get(m.id)===i;input.addEventListener('change',()=>predictions.set(m.id,i));label.append(input,node('span',choice));$('answers').append(label);});
 $('explain-task').hidden=!['predict','project'].includes(m.mode);$('reasoning').value='';$('feedback').hidden=true;$('hint-text').hidden=true;$('hint-button').disabled=false;$('step-button').disabled=false;$('run-button').disabled=false;$('restore-code').disabled=false;$('reset-button').hidden=true;$('trace-text').textContent='Lee el programa o prepara tu solución. Comprueba el estado paso a paso.';$('trace-counter').textContent='Sin ejecutar';$('world-status').textContent='Estado inicial';$('task-help').textContent=m.mode==='predict'?'Elige una predicción antes de ejecutar.':'Puedes probar, cambiar el programa y volver a ejecutar.';
 renderState(RobotJava.execute('',m.initial).initial,true);editing();reference();renderRoute();$('java-context').textContent='javac Mision.java\njava Mision\n\nIncluye main(), tus clases, los métodos auxiliares y la API Robot.\nRequiere un JDK instalado.';$('inspector').open=m.chapter===5||m.chapter===6;if(manual)AtlasAdventure.view(enter?'mission':'map',enter);
}
function start(){
 if(result)return true;if(current.mode==='predict'&&!predictions.has(current.id)){$('task-help').textContent='Primero elige una predicción. Después compárala con la ejecución.';$('answers').querySelector('input')?.focus();return false;}
 const code=source();result={...RobotJava.execute(code,current.initial),source:code};cursor=-1;$('answers').disabled=true;$('restore-code').disabled=true;editing();$('reset-button').hidden=false;renderState(result.initial??RobotJava.execute('',current.initial).initial,true);return true;
}
function nextStep(){if(!start())return;if(cursor+1<result.trace.length){cursor++;const event=result.trace[cursor];renderState(event);showCode(result.source,event.line);$('trace-text').textContent=`Línea ${event.line}: ${event.message}`;$('trace-counter').textContent=`Paso ${cursor+1} de ${result.trace.length}`;$('world-status').textContent='Ejecutando';}if(cursor+1>=result.trace.length)finish();}
function finish(){
 stop();$('step-button').disabled=true;$('run-button').disabled=true;$('restore-code').disabled=false;$('world-status').textContent=result.error?'Prueba interrumpida':'Programa terminado';const valid=grade(current,result,result.source),correct=current.mode!=='predict'||predictions.get(current.id)===current.answer,success=valid&&correct;
 $('feedback').hidden=false;$('feedback').className='feedback'+(success?'':' error');$('feedback-title').textContent=success?'Misión resuelta':result.error?'El programa necesita un ajuste':!correct?'Compara tu predicción':'El objetivo todavía no se cumple';
 $('feedback-text').textContent=result.error?`Línea ${result.error.line}: ${result.error.message}`:success?current.explanation:!correct?'La ejecución muestra un resultado distinto al que elegiste. Sigue los cambios y vuelve a intentarlo.':`Resultado actual: ${summary(result.final)}. Objetivo: ${current.goal}`;
 $('feedback-extra').replaceChildren();if(success&&$('reasoning').value.trim())$('feedback-extra').append(node('p','Tu explicación: '+$('reasoning').value.trim()));if(success&&current.number===90)$('feedback-extra').append(node('p',completed.size>=89?'¡Completaste el recorrido! Descarga y ejecuta el proyecto final en Java.':'Completaste la misión final. Puedes volver a las misiones pendientes.'));
 AtlasAdventure.celebrate(success);$('run-button').textContent='Ejecutar';$('next-button').hidden=!success||current.number===90;if(success){completed.add(current.id);renderRoute();queueSave(true);}if(result.error){showCode(result.source,result.error.line);$('trace-text').textContent='Error en línea '+result.error.line+': '+result.error.message;}$('feedback-title').focus({preventScroll:true});
}
function summary(s){if(!s)return 'sin estado válido';return s.objects.filter(o=>o.robot).map(o=>`${o.robot.name} (${o.robot.x}, ${o.robot.y}), carga ${o.robot.cargo}, entregas ${o.robot.delivered}`).join('; ')+(s.output.length?'; consola: '+s.output.join(' / '):'');}
function reset(){stop();result=null;cursor=-1;$('feedback').hidden=true;$('step-button').disabled=false;$('run-button').disabled=false;$('restore-code').disabled=false;$('answers').disabled=false;$('reset-button').hidden=true;$('trace-counter').textContent='Sin ejecutar';$('trace-text').textContent='Prueba reiniciada. Tu código sigue disponible para corregirlo.';$('world-status').textContent='Estado inicial';renderState(RobotJava.execute('',current.initial).initial,true);$('run-button').textContent='Ejecutar';editing();}
function queueSave(immediate=false){revision++;$('save-status').textContent='Cambios pendientes de guardar…';clearTimeout(saveTimer);if(immediate)flushSave();else saveTimer=setTimeout(flushSave,400);}
async function flushSave(){if(saving)return;saving=true;$('save-retry').hidden=true;try{while(savedRevision<revision){const version=revision,body={mission:current.id,completed:[...completed]};$('save-status').textContent='Guardando en tu cuenta…';const response=await fetch('/api/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),keepalive:true});if(!response.ok)throw new Error();const data=await response.json();if(!data.saved)throw new Error();savedRevision=version;}$('save-status').textContent='Avance guardado en tu cuenta.';}catch{$('save-status').textContent='Sin guardar. Conservamos tu avance en esta sesión.';$('save-retry').hidden=false;}finally{saving=false;}}
async function loadProgress(){try{const response=await fetch('/api/progress');if(!response.ok)throw new Error();const data=await response.json();if(!Array.isArray(data.completed))throw new Error();for(const id of data.completed)if(levels.some(m=>m.id===id))completed.add(id);if(!touched&&!location.hash){const last=levels.find(m=>m.id===data.lastMission);if(last)select(last);}renderRoute();if(!revision)$('save-status').textContent='Avance sincronizado con tu cuenta.';}catch{$('save-status').textContent='No pudimos cargar el avance. Puedes continuar y reintentar.';$('save-retry').hidden=false;}}
$('pause-button').addEventListener('click',stop);
$('step-button').addEventListener('click',()=>{touched=true;stop();nextStep();});$('run-button').addEventListener('click',()=>{touched=true;if(!start()||timer)return;nextStep();if(!$('run-button').disabled){$('pause-button').hidden=false;$('run-button').textContent='Ejecutando…';timer=setInterval(nextStep,matchMedia('(prefers-reduced-motion: reduce)').matches?100:460);}});
$('reset-button').addEventListener('click',reset);$('retry-button').addEventListener('click',()=>{reset();(current.mode==='predict'?$('answers').querySelector('input'):current.mode==='order'?$('parsons').querySelector('button'):$('code-editor'))?.focus();});$('next-button').addEventListener('click',()=>select(levels[current.number],true));
$('restore-code').addEventListener('click',()=>{drafts.delete(current.id);arrangements.delete(current.id);$('code-editor').value=current.code;reset();});$('hint-button').addEventListener('click',()=>{$('hint-text').hidden=false;$('hint-text').textContent=`Pista ${Math.min(++hintCount,current.hints.length)}: ${current.hints[Math.min(hintCount-1,current.hints.length-1)]}`;});
$('code-editor').addEventListener('input',()=>drafts.set(current.id,$('code-editor').value));$('code-editor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const editor=e.target;editor.setRangeText('  ',editor.selectionStart,editor.selectionEnd,'end');drafts.set(current.id,editor.value);}});
$('save-retry').addEventListener('click',async()=>{await loadProgress();if(revision>savedRevision)await flushSave();});
window.addEventListener('pagehide',()=>{if(revision>savedRevision)fetch('/api/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mission:current.id,completed:[...completed]}),keepalive:true}).catch(()=>{});});
$('download-java').addEventListener('click',()=>{try{const text=JavaExport.exportJava(current,source()),url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),link=node('a');link.href=url;link.download='Mision.java';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);$('java-context').textContent='Mision.java generado con tu código actual.\n\njavac Mision.java\njava Mision\n\nLa API Robot está incluida; no necesita bibliotecas adicionales.';}catch(error){$('java-context').textContent='Corrige primero la sintaxis para generar el archivo: '+error.message;}});
AtlasAdventure.init((mission,enter)=>select(mission,true,enter),stop);select(current);loadProgress();
})();
