'use strict';
(() => {
const V=(type,value)=>({type,value}), VOID=()=>V('void',null), int=n=>V('int',n), bool=b=>V('boolean',b);
class JavaError extends Error {constructor(message,line=1){super(message);this.line=line;}}
function tokenize(source){
  if(source.length>18000)throw new JavaError('El programa es demasiado largo para esta misión.');
  const tokens=[];let pos=0,line=1;
  const pattern=/^(\s+|\/\/[^\n]*|\/\*[\s\S]*?\*\/|"(?:\\.|[^"\\])*"|\d+(?:\.\d+)?|[A-Za-z_$][\w$]*|==|!=|<=|>=|&&|\|\||\+\+|--|\+=|-=|\*=|\/=|[{}()[\];,.+\-*/%<>=!?:])/;
  while(pos<source.length){const match=source.slice(pos).match(pattern);if(!match)throw new JavaError(`No reconozco el símbolo ${source[pos]}.`,line);const text=match[0], start=pos;pos+=text.length;if(!/^\s|^\/\/|^\/\*/.test(text))tokens.push({text,line,start,end:pos});line+=(text.match(/\n/g)||[]).length;}
  tokens.push({text:'<end>',line,start:pos,end:pos});return tokens;
}
class Parser {
  constructor(source){this.source=source;this.tokens=tokenize(source);this.i=0;}
  peek(n=0){return this.tokens[this.i+n]?.text??'<end>';}
  take(text){if(this.peek()===text){return this.tokens[this.i++];}return null;}
  expect(text){const token=this.take(text);if(!token)throw new JavaError(`Se esperaba «${text}», pero encontré «${this.peek()}».`,this.tokens[this.i].line);return token;}
  name(){const t=this.tokens[this.i++];if(!/^[A-Za-z_$][\w$]*$/.test(t.text))throw new JavaError('Se esperaba un nombre.',t.line);return t.text;}
  mods(){const modifiers=[];while(['public','private','protected','static','abstract','final','@Override'].includes(this.peek()))modifiers.push(this.tokens[this.i++].text);return modifiers;}
  type(){let name=this.name();if(this.take('<')){while(!this.take('>')){if(this.peek()==='<end>')this.expect('>');this.i++;} }while(this.take('[')){this.expect(']');name+='[]';}return name;}
  parameters(){const params=[];this.expect('(');if(!this.take(')')){do{params.push({type:this.type(),name:this.name()});}while(this.take(','));this.expect(')');}return params;}
  block(){const t=this.expect('{'),nodes=[];while(!this.take('}')){if(this.peek()==='<end>')this.expect('}');nodes.push(this.statement());}return{kind:'block',nodes,line:t.line,start:t.start,end:this.tokens[this.i-1].end};}
  classDecl(){const t=this.tokens[this.i++],name=this.name();let parent=null;const interfaces=[];if(this.take('extends'))parent=this.name();if(this.take('implements')){do{interfaces.push(this.name());}while(this.take(','));}this.expect('{');const fields=[],methods=[];
    while(!this.take('}')){if(this.peek()==='<end>')this.expect('}');const start=this.tokens[this.i],mods=this.mods();let type,member;
      if(this.peek()===name&&this.peek(1)==='('){member=this.name();type=name;}else{type=this.type();member=this.name();}
      if(this.peek()==='('){const params=this.parameters(),body=this.take(';')?null:this.block();methods.push({kind:'method',name:member,type,params,body,mods,line:start.line,owner:name});}
      else{const init=this.take('=')?this.expression():null;this.expect(';');fields.push({name:member,type,init,mods,line:start.line,owner:name});}
    }return{kind:'class',name,parent,interfaces,fields,methods,isInterface:t.text==='interface',line:t.line,start:t.start,end:this.tokens[this.i-1].end};
  }
  declarationAhead(){const saved=this.i;try{this.mods();this.type();const yes=/^[A-Za-z_$][\w$]*$/.test(this.peek())&&['=',';',',','('].includes(this.peek(1));this.i=saved;return yes;}catch{this.i=saved;return false;}}
  declaration(semicolon=true){const token=this.tokens[this.i],mods=this.mods(),type=this.type(),name=this.name();if(this.peek()==='('){const params=this.parameters(),body=this.block();return{kind:'method',name,type,params,body,mods,line:token.line,start:token.start,end:this.tokens[this.i-1].end,owner:'Mision'};}
    const init=this.take('=')?this.expression():null;if(semicolon)this.expect(';');return{kind:'declare',type,name,init,mods,line:token.line,start:token.start,end:this.tokens[this.i-1].end};
  }
  statement(){const token=this.tokens[this.i];let node;
    if(this.peek()==='{')return this.block();
    if(['class','interface'].includes(this.peek()))return this.classDecl();
    if(this.take('if')){this.expect('(');const test=this.expression();this.expect(')');const yes=this.statement(),no=this.take('else')?this.statement():null;node={kind:'if',test,yes,no};}
    else if(this.take('while')){this.expect('(');const test=this.expression();this.expect(')');node={kind:'while',test,body:this.statement()};}
    else if(this.take('for')){this.expect('(');const init=this.peek()===';'?null:this.declarationAhead()?this.declaration(false):{kind:'expr',expr:this.expression(),line:token.line};this.expect(';');const test=this.peek()===';'?null:this.expression();this.expect(';');const update=this.peek()===')'?null:this.expression();this.expect(')');node={kind:'for',init,test,update,body:this.statement()};}
    else if(this.take('return')){const expr=this.peek()===';'?null:this.expression();this.expect(';');node={kind:'return',expr};}
    else if(this.take('break')){this.expect(';');node={kind:'break'};}
    else if(this.take('continue')){this.expect(';');node={kind:'continue'};}
    else if(this.take(';'))node={kind:'empty'};
    else if(this.declarationAhead())return this.declaration();
    else{const expr=this.expression();this.expect(';');node={kind:'expr',expr};}
    return{...node,line:token.line,start:token.start,end:this.tokens[this.i-1].end};
  }
  expression(min=0){let left=this.unary();const priorities={'=':1,'+=':1,'-=':1,'*=':1,'/=':1,'||':2,'&&':3,'==':4,'!=':4,'<':5,'>':5,'<=':5,'>=':5,'+':6,'-':6,'*':7,'/':7,'%':7};
    while(priorities[this.peek()]&&priorities[this.peek()]>=min){const op=this.tokens[this.i++],rank=priorities[op.text],right=this.expression(rank+(rank===1?0:1));left={kind:rank===1?'assign':'binary',op:op.text,left,right,line:op.line};}return left;
  }
  unary(){const token=this.tokens[this.i];if(['!','-','+','++','--'].includes(this.peek())){this.i++;return{kind:'unary',op:token.text,expr:this.unary(),line:token.line};}let node;
    if(this.take('(')){node=this.expression();this.expect(')');}
    else if(this.take('new')){const type=this.name();if(this.take('<')){while(!this.take('>')){if(this.peek()==='<end>')this.expect('>');this.i++;}}
      if(this.take('[')){const size=this.peek()===']'?null:this.expression();this.expect(']');let elements=null;if(this.take('{')){elements=[];if(!this.take('}')){do{elements.push(this.expression());}while(this.take(',')&&this.peek()!=='}');this.expect('}');}}node={kind:'newArray',type,size,elements,line:token.line};}
      else node={kind:'new',type,args:this.arguments(),line:token.line};
    }else if(/^"/.test(this.peek())){this.i++;try{node={kind:'literal',value:V('String',JSON.parse(token.text)),line:token.line};}catch{throw new JavaError('Cadena de texto no válida.',token.line);}}
    else if(/^\d/.test(this.peek())){this.i++;node={kind:'literal',value:V(token.text.includes('.')?'double':'int',Number(token.text)),line:token.line};}
    else if(['true','false','null'].includes(this.peek())){this.i++;node={kind:'literal',value:token.text==='null'?V('null',null):bool(token.text==='true'),line:token.line};}
    else node={kind:'id',name:this.name(),line:token.line};
    while(true){if(this.take('.'))node={kind:'member',object:node,name:this.name(),line:token.line};else if(this.peek()==='(')node={kind:'call',callee:node,args:this.arguments(),line:token.line};else if(this.take('[')){const index=this.expression();this.expect(']');node={kind:'index',object:node,index,line:token.line};}else if(['++','--'].includes(this.peek())){node={kind:'post',op:this.tokens[this.i++].text,expr:node,line:token.line};}else break;}return node;
  }
  arguments(){this.expect('(');const args=[];if(!this.take(')')){do{args.push(this.expression());}while(this.take(','));this.expect(')');}return args;}
  parse(){const nodes=[];while(this.peek()!=='<end>')nodes.push(this.statement());return nodes;}
}
class Scope {constructor(parent=null,self=null,owner='Mision'){this.parent=parent;this.self=self??parent?.self;this.owner=owner??parent?.owner;this.values=new Map();}find(name){if(this.values.has(name))return this;return this.parent?.find(name);}}
const format=value=>{if(value==null)return'null';if(typeof value==='object')return value.array?`[${value.items.map(v=>format(v.value)).join(', ')}]`:value.list?`[${value.items.map(v=>format(v.value)).join(', ')}]`:`${value.cls} #${value.id}`;return String(value);};
class Interpreter {
  constructor(source,initial={}){
    this.source=source;this.ast=new Parser(source).parse();this.classes=new Map();this.helpers=new Map();this.heap=[];this.output=[];this.stack=['jugar'];this.steps=0;this.iterations=0;
    this.world={width:6,height:5,boxes:structuredClone(initial.boxes??[]),walls:structuredClone(initial.walls??[]),chargers:structuredClone(initial.chargers??[[0,2]]),targets:structuredClone(initial.targets??[])};
    this.classes.set('Robot',{name:'Robot',fields:[],methods:[],parent:null,native:true});
    for(const node of this.ast){if(node.kind==='class'){if(this.classes.has(node.name))throw new JavaError('La clase ya existe: '+node.name,node.line);this.classes.set(node.name,node);}if(node.kind==='method')this.helpers.set(node.name,node);}
    for(const c of this.classes.values()){const visited=new Set();for(let p=c;p;p=this.classes.get(p.parent)){if(visited.has(p.name))throw new JavaError('La herencia contiene un ciclo.',c.line);visited.add(p.name);if(p.parent&&!this.classes.has(p.parent))throw new JavaError('La clase base no existe: '+p.parent,c.line);}for(const name of c.interfaces??[])if(!this.classes.get(name)?.isInterface)throw new JavaError('La interfaz no existe: '+name,c.line);}
    this.global=new Scope();const atlas=this.robotObject('Miaubit',initial.robot??{});this.global.values.set('robot',V('Robot',atlas));
    if(initial.helper){const helper=this.robotObject('Luna',{y:3,...initial.helper});this.global.values.set('ayudante',V('Robot',helper));}
  }
  allocate(object){if(this.heap.length>=80)throw new JavaError('El laboratorio permite observar hasta 80 objetos por prueba. Revisa cuántos creas en el bucle.');this.heap.push(object);}
  robotObject(name,props={},cls='Robot'){const object={id:this.heap.length+1,cls,fields:{},robot:{name,x:0,y:Math.min(2+this.heap.filter(o=>o.robot).length,4),dir:0,energy:20,cargo:0,delivered:0,...props}};this.allocate(object);return object;}
  isA(type,target){if(type===target)return true;const c=this.classes.get(type);return !!c&&(c.interfaces?.includes(target)||c.parent&&this.isA(c.parent,target));}
  checked(type,value,line){if(type===value.type)return value;if(type==='double'&&['int','Integer'].includes(value.type))return V('double',value.value);if(type==='Integer'&&value.type==='int')return V('Integer',value.value);if(type==='int'&&value.type==='Integer')return int(value.value);if(value.type==='null'&&!['int','double','boolean','void'].includes(type))return V(type,null);if(value.value&&this.isA(value.value.cls,type))return V(type,value.value);throw new JavaError(`No puedes guardar ${value.type} en una variable de tipo ${type}.`,line);}
  needBoolean(value,line){if(value.type!=='boolean')throw new JavaError('La condición debe ser boolean: true o false.',line);return value.value;}
  needNumber(value,line){if(!['int','double','Integer'].includes(value.type))throw new JavaError('Esta operación necesita un número.',line);return value.value;}
  numberOp(op,a,b,line){if(op==='+'&&(a.type==='String'||b.type==='String'))return V('String',format(a.value)+format(b.value));const x=this.needNumber(a,line),y=this.needNumber(b,line);if(['<','>','<=','>='].includes(op))return bool(op==='<'?x<y:op==='>'?x>y:op==='<='?x<=y:x>=y);if((op==='/'||op==='%')&&y===0)throw new JavaError('División por cero: revisa el divisor.',line);const type=a.type==='double'||b.type==='double'?'double':'int';const result=op==='+'?x+y:op==='-'?x-y:op==='*'?x*y:op==='/'?(type==='int'?Math.trunc(x/y):x/y):x%y;return V(type,type==='int'?result|0:result);}
  fieldInfo(object,name){let cls=this.classes.get(object.cls);while(cls){const field=cls.fields.find(f=>f.name===name);if(field)return field;cls=this.classes.get(cls.parent);}return null;}
  access(object,name,scope,line){const field=this.fieldInfo(object,name);if(!field)throw new JavaError(`El objeto ${object.cls} no tiene un atributo llamado ${name}.`,line);if(field.mods.includes('private')&&scope.owner!==field.owner)throw new JavaError(`«${name}» es private. Accede mediante un método público de ${field.owner}.`,line);return object.fields[name];}
  *lvalue(node,scope){if(node.kind==='id'){const found=scope.find(node.name);if(found)return{get:()=>found.values.get(node.name),set:v=>found.values.set(node.name,this.checked(found.values.get(node.name).type,v,node.line))};if(scope.self&&this.fieldInfo(scope.self,node.name)){const v=this.access(scope.self,node.name,scope,node.line);return{get:()=>v,set:value=>{scope.self.fields[node.name]=this.checked(v.type,value,node.line);}};}throw new JavaError(`«${node.name}» todavía no está declarada o salió de alcance.`,node.line);}
    if(node.kind==='member'){const o=yield* this.eval(node.object,scope);if(!o.value)throw new JavaError('La referencia es null.',node.line);const v=this.access(o.value,node.name,scope,node.line);return{get:()=>o.value.fields[node.name],set:value=>{o.value.fields[node.name]=this.checked(v.type,value,node.line);}};}
    if(node.kind==='index'){const a=yield* this.eval(node.object,scope),i=yield* this.eval(node.index,scope);const index=this.needNumber(i,node.line);if(!a.value?.array||!Number.isInteger(index)||index<0||index>=a.value.items.length)throw new JavaError('Índice fuera de los límites del arreglo.',node.line);return{get:()=>a.value.items[index],set:v=>{a.value.items[index]=this.checked(a.value.elementType,v,node.line);}};}
    throw new JavaError('El lado izquierdo debe ser una variable o atributo modificable.',node.line);
  }
  *eval(node,scope){
    if(node.kind==='literal')return node.value;
    if(node.kind==='id'){if(node.name==='this'){if(!scope.self)throw new JavaError('this solo existe dentro de un objeto.',node.line);return V(scope.self.cls,scope.self);}const found=scope.find(node.name);if(found)return found.values.get(node.name);if(scope.self&&this.fieldInfo(scope.self,node.name))return this.access(scope.self,node.name,scope,node.line);if(['System','Math'].includes(node.name))return V('builtin',node.name);if(this.classes.has(node.name))return V('class',node.name);throw new JavaError(`«${node.name}» no está declarada o salió de alcance.`,node.line);}
    if(node.kind==='member'){const o=yield* this.eval(node.object,scope);if(o.value==='System'&&node.name==='out')return V('builtin','stdout');if(o.value?.array&&node.name==='length')return int(o.value.items.length);if(!o.value)throw new JavaError('La referencia es null.',node.line);return this.access(o.value,node.name,scope,node.line);}
    if(node.kind==='index'){const ref=yield* this.lvalue(node,scope);return ref.get();}
    if(node.kind==='binary'){const left=yield* this.eval(node.left,scope);if(node.op==='&&'){if(!this.needBoolean(left,node.line))return bool(false);return bool(this.needBoolean(yield* this.eval(node.right,scope),node.line));}if(node.op==='||'){if(this.needBoolean(left,node.line))return bool(true);return bool(this.needBoolean(yield* this.eval(node.right,scope),node.line));}const right=yield* this.eval(node.right,scope);if(['==','!='].includes(node.op)){if(left.type==='String'||right.type==='String')throw new JavaError('En estas misiones compara texto con equals(), no con ==.',node.line);const equal=left.value===right.value;return bool(node.op==='=='?equal:!equal);}return this.numberOp(node.op,left,right,node.line);}
    if(node.kind==='assign'){const ref=yield* this.lvalue(node.left,scope),right=yield* this.eval(node.right,scope),value=node.op==='='?right:this.numberOp(node.op[0],ref.get(),right,node.line);ref.set(value);return ref.get();}
    if(node.kind==='post'||node.kind==='unary'){if(['++','--'].includes(node.op)){const ref=yield* this.lvalue(node.expr,scope),old=ref.get();ref.set(this.numberOp(node.op==='++'?'+':'-',old,int(1),node.line));return node.kind==='post'?old:ref.get();}const v=yield* this.eval(node.expr,scope);if(node.op==='!')return bool(!this.needBoolean(v,node.line));return V(v.type,node.op==='-'?-this.needNumber(v,node.line):this.needNumber(v,node.line));}
    if(node.kind==='newArray'){const items=[];if(node.elements){for(const e of node.elements)items.push(this.checked(node.type,yield* this.eval(e,scope),node.line));}else{const size=this.needNumber(yield* this.eval(node.size,scope),node.line);if(!Number.isInteger(size)||size<0||size>100)throw new JavaError('El tamaño del arreglo debe estar entre 0 y 100.',node.line);for(let i=0;i<size;i++)items.push(this.defaultValue(node.type));}const array={id:this.heap.length+1,cls:node.type+'[]',array:true,elementType:node.type,items,fields:{}};this.allocate(array);return V(array.cls,array);}
    if(node.kind==='new'){const args=[];for(const a of node.args)args.push(yield* this.eval(a,scope));if(node.type==='ArrayList'){const list={id:this.heap.length+1,cls:'ArrayList',list:true,items:[],fields:{}};this.allocate(list);return V('ArrayList',list);}const cls=this.classes.get(node.type);if(!cls)throw new JavaError('La clase no existe: '+node.type,node.line);if(cls.isInterface||cls.mods?.includes('abstract'))throw new JavaError('No puedes crear directamente una interfaz.',node.line);
      if(cls.native&&(args.length!==1||args[0].type!=='String'))throw new JavaError('El constructor Robot espera un nombre String.',node.line);
      let object;if(this.isA(node.type,'Robot'))object=this.robotObject(args[0]?.type==='String'?args[0].value:node.type,{},node.type);else{object={id:this.heap.length+1,cls:node.type,fields:{}};this.allocate(object);}
      const hierarchy=[];for(let c=cls;c;c=this.classes.get(c.parent))hierarchy.unshift(c);
      for(const c of hierarchy)for(const f of c.fields){object.fields[f.name]=f.init?this.checked(f.type,yield* this.eval(f.init,new Scope(null,object,c.name)),f.line):this.defaultValue(f.type);}
      const constructor=cls.methods.find(m=>m.name===cls.name);if(constructor)yield* this.invoke(constructor,object,args,node.line,scope);else if(!cls.native&&args.length)throw new JavaError('La clase no tiene un constructor con esos parámetros.',node.line);return V(node.type,object);
    }
    if(node.kind==='call'){const args=[];for(const arg of node.args)args.push(yield* this.eval(arg,scope));if(node.callee.kind==='id'){if(node.callee.name==='super'){if(!scope.self?.robot)throw new JavaError('super() solo está disponible para constructores derivados de Robot en este entorno.',node.line);if(args[0])scope.self.robot.name=args[0].value;return VOID();}const helper=this.helpers.get(node.callee.name);if(helper)return yield* this.invoke(helper,null,args,node.line,scope);if(scope.self)return yield* this.callMethod(V(scope.self.cls,scope.self),node.callee.name,args,scope,node.line);throw new JavaError('Método desconocido: '+node.callee.name,node.line);}if(node.callee.kind!=='member')throw new JavaError('Llamada no válida.',node.line);const object=yield* this.eval(node.callee.object,scope);return yield* this.callMethod(object,node.callee.name,args,scope,node.line);}
    throw new JavaError('Expresión no admitida en este entorno.',node.line);
  }
  defaultValue(type){return V(type,type==='boolean'?false:['int','double','Integer'].includes(type)?0:null);}
  *callMethod(receiver,name,args,scope,line){
    if(receiver.value==='stdout'&&name==='println'){if(args.length!==1||args[0].type==='void')throw new JavaError('println() espera un valor; void no es un valor.',line);this.output.push(format(args[0].value));return VOID();}
    if(receiver.value==='Math'){const nums=args.map(v=>this.needNumber(v,line));if(!['min','max','abs'].includes(name)||args.length!==(name==='abs'?1:2))throw new JavaError('Método Math o cantidad de argumentos no admitidos.',line);return V(args.some(v=>v.type==='double')?'double':'int',Math[name](...nums));}
    if(receiver.type==='String'){if(name==='equals')return bool(receiver.value===args[0]?.value);if(name==='length')return int(receiver.value.length);throw new JavaError('Método de String no admitido.',line);}
    const object=receiver.value;if(!object)throw new JavaError('No puedes llamar un método sobre null.',line);
    if(object.list){if(name==='add'){if(args.length!==1)throw new JavaError('add() espera un elemento.',line);if(object.items.length>=100)throw new JavaError('El laboratorio limita las listas a 100 elementos.',line);object.items.push(args[0]);return bool(true);}if(name==='size')return int(object.items.length);if(name==='get'){const i=args[0]?.value;if(!Number.isInteger(i)||i<0||i>=object.items.length)throw new JavaError('Índice fuera de la lista.',line);return object.items[i];}throw new JavaError('Método de ArrayList no admitido.',line);}
    let cls=this.classes.get(object.cls);while(cls){const method=cls.methods.find(m=>m.name===name);if(method){if(method.mods.includes('private')&&scope.owner!==method.owner)throw new JavaError('Ese método es private.',line);return yield* this.invoke(method,object,args,line,scope);}cls=this.classes.get(cls.parent);}
    if(object.robot)return this.robotMethod(object,name,args,line);
    throw new JavaError(`La clase ${object.cls} no tiene el método ${name}().`,line);
  }
  robotMethod(object,name,args,line){const r=object.robot,dirs=[[1,0],[0,1],[-1,0],[0,-1]],coords=()=>[r.x+dirs[r.dir][0],r.y+dirs[r.dir][1]];
    const clear=(x,y)=>x>=0&&x<6&&y>=0&&y<5&&!this.world.walls.some(w=>w[0]===x&&w[1]===y);
    const move=(dx,dy)=>{if(!clear(r.x+dx,r.y+dy))throw new JavaError('El robot intentó salir del mapa o atravesar un obstáculo. Comprueba el camino.',line);if(r.energy<1)throw new JavaError('El robot se quedó sin energía. Necesita recargar.',line);r.x+=dx;r.y+=dy;r.energy--;};
    const natives={avanzar:()=>{const [dx,dy]=dirs[r.dir];move(dx,dy);return VOID();},este:()=>{move(1,0);return VOID();},oeste:()=>{move(-1,0);return VOID();},norte:()=>{move(0,-1);return VOID();},sur:()=>{move(0,1);return VOID();},girarDerecha:()=>{r.dir=(r.dir+1)%4;return VOID();},girarIzquierda:()=>{r.dir=(r.dir+3)%4;return VOID();},getX:()=>int(r.x),getY:()=>int(r.y),getEnergia:()=>int(r.energy),getCarga:()=>int(r.cargo),getEntregas:()=>int(r.delivered),getNombre:()=>V('String',r.name),puedeAvanzar:()=>bool(clear(...coords())&&r.energy>0),hayCaja:()=>bool(this.world.boxes.some(b=>b[0]===r.x&&b[1]===r.y&&b[2]>0)),recoger:()=>{const box=this.world.boxes.find(b=>b[0]===r.x&&b[1]===r.y&&b[2]>0);if(!box)throw new JavaError('Aquí no hay una caja para recoger.',line);box[2]--;r.cargo++;return VOID();},dejar:()=>{if(r.cargo<1)throw new JavaError('El inventario del robot está vacío.',line);r.cargo--;r.delivered++;return VOID();},recargar:()=>{if(!this.world.chargers.some(c=>c[0]===r.x&&c[1]===r.y))throw new JavaError('Para recargar debes estar en una estación ⚡.',line);r.energy=20;return VOID();},gastar:()=>{const n=this.needNumber(args[0],line);if(n<0||n>r.energy)throw new JavaError('No puedes gastar más energía de la disponible.',line);r.energy-=n;return VOID();}};
    if(!natives[name])throw new JavaError(`Robot no tiene el método ${name}().`,line);const expected=name==='gastar'?1:0;if(args.length!==expected)throw new JavaError(`${name}() espera ${expected} parámetros.`,line);return natives[name]();
  }
  *invoke(method,self,args,line,callerScope=this.global){if(!method.body)throw new JavaError('Falta implementar el método '+method.name+'().',line);if(args.length!==method.params.length)throw new JavaError(`${method.name}() espera ${method.params.length} parámetros.`,line);if(this.stack.length>=24)throw new JavaError('Demasiadas llamadas anidadas: revisa si un método se llama a sí mismo sin terminar.',line);const scope=new Scope(null,self,method.owner);method.params.forEach((p,i)=>scope.values.set(p.name,this.checked(p.type,args[i],line)));this.stack.push(method.name);yield this.event(method.line,`Entras en ${method.name}(). Cada parámetro recibe el valor de su argumento.`,scope);let returned=VOID();try{yield* this.execute(method.body,scope);}catch(control){if(control?.kind==='return')returned=control.value;else throw control;}finally{this.stack.pop();}yield this.event(line,`Vuelves de ${method.name}() a la instrucción que lo llamó. Sus parámetros dejan de estar en alcance.`,callerScope);if(method.name===method.owner)return VOID();if(method.type==='void'){if(returned.type!=='void')throw new JavaError('Un método void no devuelve un valor.',line);return VOID();}return this.checked(method.type,returned,line);}
  *execute(node,scope){
    if(node.kind==='class'||node.kind==='method'||node.kind==='empty')return;
    if(node.kind==='block'){const inner=new Scope(scope,scope.self,scope.owner);for(const child of node.nodes)yield* this.execute(child,inner);return;}
    if(node.kind==='declare'){if(scope.find(node.name))throw new JavaError('La variable ya está declarada en este alcance: '+node.name,node.line);if(!node.init)throw new JavaError('Inicializa esta variable antes de usarla en la misión.',node.line);const value=this.checked(node.type,yield* this.eval(node.init,scope),node.line);scope.values.set(node.name,value);yield this.event(node.line,`${node.name} (${node.type}) = ${format(value.value)}.`,scope);return;}
    if(node.kind==='expr'){const value=yield* this.eval(node.expr,scope);yield this.event(node.line,value.type==='void'?'La instrucción terminó y actualizó el estado.':`Resultado: ${format(value.value)}.`,scope);return;}
    if(node.kind==='if'){const result=this.needBoolean(yield* this.eval(node.test,scope),node.line);yield this.event(node.line,`La condición da ${result}: ${result?'entras en if':'eliges else, si existe'}.`,scope);if(result)yield* this.execute(node.yes,scope);else if(node.no)yield* this.execute(node.no,scope);return;}
    if(node.kind==='for'||node.kind==='while'){const inner=node.kind==='for'?new Scope(scope,scope.self,scope.owner):scope;if(node.init)yield* this.execute(node.init,inner);let count=0;while(true){if(++count>160)throw new JavaError('El bucle supera 160 vueltas. Comprueba que la condición pueda llegar a false.',node.line);const result=node.test?this.needBoolean(yield* this.eval(node.test,inner),node.line):true;yield this.event(node.line,`Condición del ${node.kind}: ${result}. ${result?'Comienza otra vuelta.':'Termina el bucle.'}`,inner);if(!result)break;let stop=false;try{yield* this.execute(node.body,inner);}catch(control){if(control?.kind==='break')stop=true;else if(control?.kind!=='continue')throw control;}if(stop)break;if(node.update){yield* this.eval(node.update,inner);yield this.event(node.line,'Actualizas el contador después de ejecutar el cuerpo.',inner);}}yield this.event(node.line,'Sales del bucle. Sus variables locales dejan de estar en alcance.',scope);return;}
    if(node.kind==='return'){const value=node.expr?yield* this.eval(node.expr,scope):VOID();yield this.event(node.line,`return devuelve ${format(value.value)} y termina la llamada.`,scope);throw{kind:'return',value};}
    if(node.kind==='break'||node.kind==='continue'){yield this.event(node.line,node.kind==='break'?'break termina el bucle.':'continue pasa a la siguiente vuelta.',scope);throw{kind:node.kind};}
  }
  snapshot(scope){const vars={},seen=new Set();for(let s=scope;s;s=s.parent)for(const [name,v] of s.values){if(seen.has(name))continue;seen.add(name);vars[name]={type:v.type,text:format(v.value),objectId:v.value?.id??null};}return{world:structuredClone(this.world),objects:this.heap.map(o=>({id:o.id,cls:o.cls,robot:o.robot?{...o.robot}:null,fields:Object.fromEntries(Object.entries(o.fields).map(([name,v])=>[name,{type:v.type,text:format(v.value),objectId:v.value?.id??null}])),items:o.items?.map(v=>format(v.value))??null})),vars,output:[...this.output],stack:[...this.stack]};}
  event(line,message,scope){if(++this.steps>1200)throw new JavaError('Demasiadas instrucciones. Simplifica la misión o revisa tus bucles.',line);return{line,message,...this.snapshot(scope)};}
  *run(){for(const node of this.ast)yield* this.execute(node,this.global);yield this.event(this.source.split('\n').length,'El programa terminó. Compara el resultado con tu objetivo.',this.global);}
}
function execute(source,initial={}){let interpreter,first;const trace=[];try{interpreter=new Interpreter(source,initial);first=interpreter.snapshot(interpreter.global);for(const event of interpreter.run())trace.push(event);return{trace,initial:first,final:interpreter.snapshot(interpreter.global),error:null};}catch(error){return{trace,initial:first??null,final:interpreter?.snapshot(interpreter.global)??null,error:{message:error instanceof JavaError?error.message:'Programa no válido: '+(error.message??'revisa la sintaxis'),line:error.line??1}};}}
const api={execute,Parser,JavaError,format};globalThis.RobotJava=api;
})();
