'use strict';
(() => {
const chapters=[
 ['Secuencias','Leer instrucciones y seguir el estado, una línea a la vez.','Una instrucción se ejecuta después de la anterior. avanzar() sigue la orientación; este(), oeste(), norte() y sur() usan direcciones del mapa.'],
 ['Variables y tipos','Guardar datos, calcular y distinguir valores.','int guarda enteros; double decimales; boolean true/false; String texto. = asigna; + suma o concatena. La división de int descarta la parte decimal.'],
 ['Decisiones','Elegir caminos con condiciones y lógica booleana.','if ejecuta su bloque cuando la condición es true. else cubre el otro caso. && exige ambas condiciones; || al menos una; ! invierte. && y || pueden evitar evaluar el segundo operando.'],
 ['Bucles','Repetir, acumular y detectar errores de límites.','for ejecuta inicio una vez, comprueba condición, ejecuta cuerpo y actualiza contador. while comprueba antes de cada vuelta. break termina; continue pasa a la siguiente vuelta.'],
 ['Métodos','Descomponer problemas y pasar argumentos.','Un método recibe parámetros locales. return devuelve un resultado y termina la llamada. void no devuelve un valor. En este laboratorio los métodos auxiliares se declaran static y reciben sus robots como parámetros.'],
 ['POO · Objetos','Clases, constructores, referencias y composición.','Una clase describe atributos y métodos. new crea un objeto. El constructor lo inicializa. this se refiere al objeto actual. Dos variables pueden apuntar al mismo objeto; copiar una referencia no lo duplica.'],
 ['POO · Diseño','Encapsulación, herencia, polimorfismo e interfaces.','private protege el estado. Un método público puede validar cambios. extends hereda comportamiento. La implementación de un método depende del objeto real, aunque la referencia sea de la clase base o de una interfaz. implements establece un contrato.'],
 ['Arreglos y listas','Procesar varios datos y objetos.','Un arreglo tiene tamaño fijo e índices desde 0 hasta length - 1. ArrayList cambia de tamaño y ofrece add(), size() y get(). Los arreglos de referencias también pueden compartir objetos.'],
 ['Expediciones','Combinar lógica y POO en problemas completos.','Planea el algoritmo, divide responsabilidades, prueba casos y explica los resultados. Estas misiones combinan conceptos anteriores. Las últimas también resuelven problemas de consola fuera del mapa.']
].map((c,i)=>({id:i,title:c[0],description:c[1],reference:c[2]}));
const levels=[];
const robot=(s,name='Atlas')=>s.objects.find(o=>o.robot?.name===name)?.robot;
const at=(x,y,name='Atlas')=>s=>robot(s,name)?.x===x&&robot(s,name)?.y===y;
const variable=(name,value)=>s=>s.vars[name]?.text===String(value);
const output=(...lines)=>s=>JSON.stringify(s.output)===JSON.stringify(lines.map(String));
const all=(...checks)=>s=>checks.every(fn=>fn(s));
const field=(cls,name,value)=>s=>s.objects.some(o=>o.cls===cls&&o.fields[name]?.text===String(value));
function add(chapter,title,mode,solution,goal,check,extra={}) {
 const n=levels.length+1;
 const m={id:'m'+String(n).padStart(2,'0'),number:n,chapter,title,mode,solution,goal,check,
 description:extra.description??'Lee el objetivo, sigue el estado y comprueba tu razonamiento con una ejecución.',
 question:mode==='predict'?'Predice el resultado antes de ejecutar.':mode==='order'?'Ordena las instrucciones con las flechas.':'Modifica el código y comprueba el resultado.',
 code:extra.starter??solution,initial:{targets:extra.target?[extra.target]:[],...extra.initial},
 hints:[extra.hint??chapters[chapter].reference,extra.hint2??'Ejecuta paso a paso. Compara la primera línea donde el estado deja de coincidir con tu plan.'],
 explanation:extra.explanation??chapters[chapter].reference,
 choices:extra.choices??[],answer:extra.answer??0,
 ...extra};
 if(mode==='predict'){m.expectedGoal=goal;m.goal='Predice el resultado y compruébalo siguiendo cada instrucción.';m.question='¿Qué resultado produce este programa?';}
 if(mode==='order')m.chunks=extra.chunks??solution.split('\n').filter(Boolean);
 levels.push(m);
}
// 01–10: tracing changes in space and state.
add(0,'Tres pasos, tres cambios','predict','robot.avanzar();\nrobot.avanzar();\nrobot.avanzar();','Termina en (3, 2).',at(3,2),{target:[3,2],choices:['(3, 2)','(0, 3)','(2, 2)'],explanation:'Atlas empieza en (0, 2), mirando al este. Cada avanzar() aumenta x en 1.'});
add(0,'El orden de una entrega','order','robot.este();\nrobot.recoger();\nrobot.este();\nrobot.dejar();','Recoge en (1, 2) y entrega en (2, 2).',all(at(2,2),s=>robot(s).delivered===1),{initial:{boxes:[[1,2,1]],targets:[[2,2]]},hint:'La caja se recoge estando en su casilla. Solo puedes dejarla después de recogerla.'});
add(0,'Girar no es avanzar','predict','robot.girarDerecha();\nrobot.avanzar();\nrobot.avanzar();','Termina en (0, 4).',at(0,4),{target:[0,4],choices:['(2, 2)','(0, 4)','(0, 0)'],answer:1,explanation:'Un giro a la derecha cambia este por sur. Girar no consume energía ni cambia de casilla.'});
add(0,'Un comando en la dirección equivocada','fix','robot.norte();\nrobot.este();\nrobot.este();','Termina en (2, 1).',at(2,1),{starter:'robot.sur();\nrobot.este();\nrobot.este();',target:[2,1],hint:'En el mapa, norte reduce y; sur aumenta y.'});
add(0,'La orientación permanece','predict','robot.girarIzquierda();\nrobot.este();\nrobot.avanzar();','Termina en (1, 1).',at(1,1),{choices:['(2, 2)','(1, 3)','(1, 1)'],answer:2,explanation:'este() mueve una casilla sin girar. Atlas sigue mirando al norte, por eso avanzar() reduce y.'});
add(0,'Rodear el muro','order','robot.norte();\nrobot.este();\nrobot.este();\nrobot.sur();','Llega a (2, 2) sin atravesar el muro.',at(2,2),{initial:{walls:[[1,2]],targets:[[2,2]]},hint:'El muro está inmediatamente al este del inicio. Sube antes de desplazarte a la derecha.'});
add(0,'Una caja antes de dejarla','fix','robot.recoger();\nrobot.este();\nrobot.dejar();','Entrega una caja en (1, 2).',all(at(1,2),s=>robot(s).delivered===1),{starter:'robot.dejar();\nrobot.este();\nrobot.recoger();',initial:{boxes:[[0,2,1]],targets:[[1,2]]}});
add(0,'Tu primer trayecto','write','robot.este();\nrobot.este();\nrobot.norte();','Llega a (2, 1).',at(2,1),{starter:'// Escribe tres movimientos.\n',target:[2,1],hint:'Puedes usar este() y norte() directamente, sin girar.'});
add(0,'Imprimir lo observado','write','robot.este();\nSystem.out.println(robot.getX());','Llega a (1, 2) e imprime 1.',all(at(1,2),output(1)),{starter:'robot.este();\n// Imprime la coordenada x.',hint:'System.out.println(robot.getX()); imprime la coordenada horizontal.'});
add(0,'Proyecto · Mensajero','project','robot.recoger();\nrobot.norte();\nrobot.este();\nrobot.este();\nrobot.sur();\nrobot.dejar();\nSystem.out.println(robot.getEntregas());','Entrega en (2, 2), esquiva el muro e imprime 1.',all(at(2,2),s=>robot(s).delivered===1,output(1)),{starter:'// Planea: recoger, rodear, entregar e imprimir.\n',initial:{boxes:[[0,2,1]],walls:[[1,2]],targets:[[2,2]]},hint:'Divide el problema en cuatro acciones. Para rodear el muro puedes usar la fila de arriba.'});
// 11–20: numbers, values and Java types.
add(1,'La variable recuerda un valor','predict','int pasos = 3;\npasos = pasos + 2;\nSystem.out.println(pasos);','Imprime 5.',output(5),{choices:['3','5','32'],answer:1,explanation:'La segunda asignación reemplaza 3 por el resultado de 3 + 2. = no es una comparación.'});
add(1,'Declarar antes de usar','order','int energia = 10;\nenergia = energia - 3;\nSystem.out.println(energia);','Imprime 7.',output(7),{hint:'La declaración crea la variable; luego puedes modificarla y leerla.'});
add(1,'Enteros y decimales','predict','int a = 5 / 2;\ndouble b = 5.0 / 2;\nSystem.out.println(a);\nSystem.out.println(b);','Imprime 2 y después 2.5.',output(2,2.5),{choices:['2.5 y 2.5','2 y 2','2 y 2.5'],answer:2});
add(1,'Un tipo compatible','fix','double distancia = 2.5;\nSystem.out.println(distancia);','Guarda e imprime 2.5.',output(2.5),{starter:'int distancia = 2.5;\nSystem.out.println(distancia);',hint:'Un valor decimal no cabe directamente en int. Cambia el tipo.'});
add(1,'Texto y suma','predict','int cajas = 2;\nSystem.out.println("Cajas: " + cajas + 1);\nSystem.out.println("Cajas: " + (cajas + 1));','Predice las dos líneas de consola.',output('Cajas: 21','Cajas: 3'),{choices:['Cajas: 3 / Cajas: 3','Cajas: 21 / Cajas: 3','Cajas: 21 / Cajas: 21'],answer:1,explanation:'Después del texto, + concatena de izquierda a derecha. Los paréntesis fuerzan primero la suma numérica.'});
add(1,'Intercambiar sin perder','order','int a = 2;\nint b = 5;\nint temporal = a;\na = b;\nb = temporal;\nSystem.out.println(a + "," + b);','Intercambia a y b e imprime 5,2.',output('5,2'),{hint:'Antes de sobrescribir a, conserva su valor en temporal.'});
add(1,'Prioridad de operaciones','fix','int total = (2 + 3) * 4;\nSystem.out.println(total);','Imprime 20.',output(20),{starter:'int total = 2 + 3 * 4;\nSystem.out.println(total);',hint:'La multiplicación ocurre antes que la suma. Usa paréntesis para cambiar el orden.'});
add(1,'Energía restante','write','int antes = robot.getEnergia();\nrobot.este();\nrobot.este();\nint usada = antes - robot.getEnergia();\nSystem.out.println(usada);','Mueve dos casillas e imprime la energía usada: 2.',all(at(2,2),output(2)),{starter:'int antes = robot.getEnergia();\n// Mueve, calcula la diferencia e imprímela.',hint:'Cada movimiento consume 1. Resta la energía final de la inicial.'});
add(1,'Reparto y sobrante','write','int cajas = 11;\nint robots = 3;\nSystem.out.println(cajas / robots);\nSystem.out.println(cajas % robots);','Imprime 3 cajas por robot y 2 sobrantes.',output(3,2),{starter:'int cajas = 11;\nint robots = 3;\n// Usa / y %. ',hint:'El cociente entero indica el reparto; el resto % indica lo que sobra.'});
add(1,'Proyecto · Presupuesto de viaje','project','int movimientos = 4;\nint coste = movimientos * 2;\nint saldo = 15 - coste;\nboolean alcanza = saldo >= 0;\nSystem.out.println("Saldo: " + saldo);\nSystem.out.println(alcanza);','Calcula 4 movimientos a 2 unidades desde un saldo de 15. Imprime Saldo: 7 y true.',output('Saldo: 7',true),{starter:'int movimientos = 4;\nint saldoInicial = 15;\n// Calcula el coste, el saldo y si alcanza.',hint:'Compara el saldo final con cero y guarda el resultado en boolean.'});
// 21–30: branches and boolean reasoning.
add(2,'Una decisión de energía','predict','if (robot.getEnergia() >= 3) {\n  robot.este();\n} else {\n  robot.recargar();\n}','Con energía 2, decide qué rama se ejecuta.',s=>robot(s).energy===20,{initial:{robot:{energy:2}},choices:['Avanza al este','Recarga y queda en (0, 2)','Hace las dos cosas'],answer:1});
add(2,'Preparar antes de entregar','order','boolean disponible = robot.hayCaja();\nif (disponible) { robot.recoger(); }\nrobot.este();\nif (robot.getCarga() > 0) { robot.dejar(); }','Entrega una caja en (1, 2).',all(at(1,2),s=>robot(s).delivered===1),{initial:{boxes:[[0,2,1]],targets:[[1,2]]}});
add(2,'El límite también cuenta','fix','int energia = 3;\nif (energia >= 3) { robot.este(); }','Con energía 3, avanza a (1, 2).',at(1,2),{starter:'int energia = 3;\nif (energia > 3) { robot.este(); }',hint:'El caso de igualdad debe pertenecer a la rama que avanza.'});
add(2,'Dos requisitos','predict','boolean autorizado = false;\nif (robot.hayCaja() && autorizado) {\n  robot.recoger();\n}\nSystem.out.println(robot.getCarga());','Predice la carga final.',output(0),{initial:{boxes:[[0,2,1]]},choices:['1','0','true'],answer:1,explanation:'&& exige true en ambos lados. Una caja disponible no basta si autorizado es false.'});
add(2,'Una alternativa basta','predict','boolean urgente = true;\nboolean permiso = false;\nif (urgente || permiso) { robot.este(); }','Predice si Atlas se mueve.',at(1,2),{choices:['Sí, hasta (1, 2)','No se mueve','Error porque permiso es false']});
add(2,'Comparar el contenido del texto','fix','String clave = "atlas";\nif (clave.equals("atlas")) { robot.este(); }','Compara la clave mediante equals() y avanza.',at(1,2),{starter:'String clave = "atlas";\nif (clave == "atlas") { robot.este(); }',hint:'En Java, equals() compara el contenido del texto. == compara referencias; aquí se bloquea para que no confundas ambas cosas.'});
add(2,'El cortocircuito protege','order','Robot otro = null;\nboolean listo = otro != null && otro.getEnergia() > 0;\nSystem.out.println(listo);','Imprime false sin llamar métodos sobre null.',output(false),{hint:'&& no evalúa la derecha cuando la izquierda es false. Comprueba null primero.'});
add(2,'Recargar si hace falta','write','if (robot.getEnergia() < 2) { robot.recargar(); }\nrobot.este();\nrobot.este();','Con energía inicial 1, recarga y llega a (2, 2).',all(at(2,2),s=>robot(s).energy===18),{starter:'// Recarga solo si faltan al menos dos movimientos.\n',initial:{robot:{energy:1},targets:[[2,2]]}});
add(2,'Elegir un desvío','write','if (!robot.puedeAvanzar()) { robot.norte(); }\nrobot.este();','Cuando el muro bloquea el frente, sube y llega a (1, 1).',at(1,1),{starter:'// Usa ! y puedeAvanzar().\n',initial:{walls:[[1,2]],targets:[[1,1]]},hint:'! invierte la respuesta del sensor. Si no puede avanzar, primero sube.'});
add(2,'Proyecto · Carga autorizada','project','boolean permiso = true;\nif (robot.hayCaja() && permiso) { robot.recoger(); }\nif (robot.getCarga() > 0) {\n  robot.este();\n  robot.dejar();\n} else {\n  System.out.println("Sin carga");\n}\nSystem.out.println(robot.getEntregas());','Recoge con permiso, entrega en (1, 2) e imprime 1.',all(at(1,2),s=>robot(s).delivered===1,output(1)),{starter:'boolean permiso = true;\n// Comprueba disponibilidad, carga y entrega.',initial:{boxes:[[0,2,1]],targets:[[1,2]]}});
// 31–40: repeated execution and boundaries.
add(3,'Contar vueltas','predict','for (int i = 0; i < 3; i++) {\n  robot.este();\n}','Predice la posición después del for.',at(3,2),{choices:['(2, 2)','(3, 2)','(4, 2)'],answer:1});
add(3,'Actualizar el while','order','int pasos = 0;\nwhile (pasos < 3) {\n  robot.este();\n  pasos++;\n}\nSystem.out.println(pasos);','Termina en (3, 2) e imprime 3.',all(at(3,2),output(3)),{chunks:['int pasos = 0;','while (pasos < 3) {\n  robot.este();\n  pasos++;\n}','System.out.println(pasos);']});
add(3,'Una vuelta de más','fix','for (int i = 0; i < 3; i++) { robot.este(); }','Haz exactamente 3 movimientos.',at(3,2),{starter:'for (int i = 0; i <= 3; i++) { robot.este(); }',hint:'Desde 0, <= 3 incluye 0, 1, 2 y 3: cuatro vueltas.'});
add(3,'Acumular','predict','int suma = 0;\nfor (int i = 1; i <= 4; i++) { suma += i; }\nSystem.out.println(suma);','Predice la suma de 1 a 4.',output(10),{choices:['4','6','10'],answer:2});
add(3,'Salir antes','predict','for (int i = 0; i < 5; i++) {\n  if (i == 2) { break; }\n  robot.este();\n}','Predice cuántos movimientos ocurren.',at(2,2),{choices:['2','3','5'],explanation:'Cuando i llega a 2, break termina el bucle antes de mover. Solo se mueve con i = 0 e i = 1.'});
add(3,'Un bucle que termina','fix','int i = 0;\nwhile (i < 3) {\n  robot.este();\n  i++;\n}','Corrige el while y termina en (3, 2).',at(3,2),{starter:'int i = 0;\nwhile (i < 3) {\n  robot.este();\n}',hint:'Sin actualizar i, la condición siempre es true. Cambia el contador dentro del cuerpo.'});
add(3,'Solo las vueltas pares','order','int total = 0;\nfor (int i = 0; i < 6; i++) {\n  if (i % 2 != 0) { continue; }\n  total += i;\n}\nSystem.out.println(total);','Imprime 6: 0 + 2 + 4.',output(6),{chunks:['int total = 0;','for (int i = 0; i < 6; i++) {\n  if (i % 2 != 0) { continue; }\n  total += i;\n}','System.out.println(total);']});
add(3,'Avanzar hasta el obstáculo','write','while (robot.puedeAvanzar()) { robot.avanzar(); }','Llega a (3, 2) y se detiene frente al muro.',at(3,2),{starter:'// Usa el sensor como condición del while.\n',initial:{walls:[[4,2]],targets:[[3,2]]}});
add(3,'Dos contadores','write','int total = 0;\nfor (int fila = 0; fila < 2; fila++) {\n  for (int columna = 0; columna < 3; columna++) { total++; }\n}\nSystem.out.println(total);','Cuenta las casillas de un rectángulo 2 × 3 con dos for. Imprime 6.',output(6),{starter:'int total = 0;\n// Un bucle para filas y otro para columnas.\n',require:'for',hint:'Por cada una de las 2 filas, recorre 3 columnas. Incrementa total dentro del bucle interior.'});
add(3,'Proyecto · Vaciado de almacén','project','while (robot.hayCaja()) { robot.recoger(); }\nfor (int i = 0; i < 3; i++) { robot.este(); }\nwhile (robot.getCarga() > 0) { robot.dejar(); }\nSystem.out.println(robot.getEntregas());','Recoge las 3 cajas, llévalas a (3, 2), entrega todas e imprime 3.',all(at(3,2),s=>robot(s).cargo===0&&robot(s).delivered===3,output(3)),{starter:'// Recoger mientras haya cajas; viajar; descargar.\n',initial:{boxes:[[0,2,3]],targets:[[3,2]]}});
// 41–50: functions, parameters, returns, decomposition.
add(4,'Un método reutilizable','predict','static void avanzarDos(Robot r) {\n  r.este();\n  r.este();\n}\navanzarDos(robot);\navanzarDos(robot);','Predice la posición después de dos llamadas.',at(4,2),{choices:['(2, 2)','(4, 2)','(0, 2)'],answer:1});
add(4,'Definir y llamar','order','static void entregar(Robot r) { r.dejar(); }\nrobot.recoger();\nrobot.este();\nentregar(robot);','Entrega una caja en (1, 2) mediante entregar().',all(at(1,2),s=>robot(s).delivered===1),{initial:{boxes:[[0,2,1]],targets:[[1,2]]},chunks:['static void entregar(Robot r) { r.dejar(); }','robot.recoger();','robot.este();','entregar(robot);']});
add(4,'El argumento correcto','fix','static void avanzar(Robot r, int pasos) {\n  for (int i = 0; i < pasos; i++) { r.este(); }\n}\navanzar(robot, 3);','Termina en (3, 2).',at(3,2),{starter:'static void avanzar(Robot r, int pasos) {\n  for (int i = 0; i < pasos; i++) { r.este(); }\n}\navanzar(robot, 2);',hint:'El parámetro pasos recibe el segundo argumento de la llamada.'});
add(4,'El parámetro es una copia','predict','static void aumentar(int n) { n++; }\nint cantidad = 2;\naumentar(cantidad);\nSystem.out.println(cantidad);','Predice el valor de cantidad.',output(2),{choices:['3','2','Error'],answer:1,explanation:'Java pasa los argumentos por valor. El parámetro n recibe una copia de 2; modificarlo no cambia cantidad.'});
add(4,'return termina la llamada','predict','static int calcular(int n) {\n  if (n > 3) { return n * 2; }\n  return n + 1;\n}\nSystem.out.println(calcular(4));','Predice el resultado de calcular(4).',output(8),{choices:['5','9','8'],answer:2});
add(4,'Devolver el tipo anunciado','fix','static int doble(int n) { return n * 2; }\nSystem.out.println(doble(3));','Imprime 6 con un método que devuelve int.',output(6),{starter:'static void doble(int n) { return n * 2; }\nSystem.out.println(doble(3));',hint:'void no devuelve valores. Cambia el tipo de retorno para que corresponda al resultado.'});
add(4,'Componer métodos','order','static int coste(int pasos) { return pasos * 2; }\nint presupuesto = 12;\nint restante = presupuesto - coste(4);\nSystem.out.println(restante);','Calcula el coste de 4 pasos e imprime el saldo 4.',output(4),{hint:'El valor devuelto por coste() puede participar en una resta.'});
add(4,'Un viaje parametrizado','write','static void viajar(Robot r, int n) {\n  for (int i = 0; i < n; i++) { r.este(); }\n}\nviajar(robot, 3);','Crea viajar(Robot r, int n), llámalo y llega a (3, 2).',at(3,2),{starter:'static void viajar(Robot r, int n) {\n  // Repite n movimientos.\n}\n// Llama al método.',require:'viajar',hint:'Recibe el robot como parámetro. Los métodos static no leen directamente las variables de jugar().'});
add(4,'Obtener un resultado','write','static boolean suficiente(int energia, int pasos) {\n  return energia >= pasos;\n}\nSystem.out.println(suficiente(2, 3));\nSystem.out.println(suficiente(3, 3));','Crea suficiente(), imprime false y true.',output(false,true),{starter:'static boolean suficiente(int energia, int pasos) {\n  // Devuelve si alcanza.\n}\nSystem.out.println(suficiente(2, 3));\nSystem.out.println(suficiente(3, 3));',require:'suficiente'});
add(4,'Proyecto · Ruta reutilizable','project','static void recogerTodo(Robot r) {\n  while (r.hayCaja()) { r.recoger(); }\n}\nstatic void viajar(Robot r, int pasos) {\n  for (int i = 0; i < pasos; i++) { r.este(); }\n}\nstatic void descargar(Robot r) {\n  while (r.getCarga() > 0) { r.dejar(); }\n}\nrecogerTodo(robot);\nviajar(robot, 4);\ndescargar(robot);','Usa tres métodos para entregar 2 cajas en (4, 2).',all(at(4,2),s=>robot(s).delivered===2&&robot(s).cargo===0),{starter:'// Define recogerTodo, viajar y descargar.\n// Después combina sus llamadas.',initial:{boxes:[[0,2,2]],targets:[[4,2]]},require:'static'});
// 51–60: construction, state, identity and composition.
const contador=`class Contador {\n  int valor;\n  Contador(int valor) { this.valor = valor; }\n  void aumentar() { valor++; }\n  int getValor() { return valor; }\n}`;
add(5,'Clase y objeto','predict',contador+'\nContador c = new Contador(2);\nc.aumentar();\nSystem.out.println(c.getValor());','Predice el valor del objeto.',output(3),{choices:['2','3','0'],answer:1,explanation:'La clase define el comportamiento. new crea c; el constructor guarda 2 y aumentar() cambia su atributo a 3.'});
add(5,'Inicializar con constructor','order','class Paquete {\n  int peso;\n  Paquete(int peso) { this.peso = peso; }\n}\nPaquete p = new Paquete(4);\nSystem.out.println(p.peso);','Crea un Paquete de peso 4 e imprímelo.',output(4),{chunks:['class Paquete {\n  int peso;\n  Paquete(int peso) { this.peso = peso; }\n}','Paquete p = new Paquete(4);','System.out.println(p.peso);']});
add(5,'this distingue atributo y parámetro','fix','class Bateria {\n  int energia;\n  Bateria(int energia) { this.energia = energia; }\n}\nBateria b = new Bateria(8);\nSystem.out.println(b.energia);','Inicializa el atributo e imprime 8.',output(8),{starter:'class Bateria {\n  int energia;\n  Bateria(int energia) { energia = energia; }\n}\nBateria b = new Bateria(8);\nSystem.out.println(b.energia);',hint:'Sin this, ambos nombres se refieren al parámetro. El atributo queda en su valor inicial 0.'});
add(5,'Dos objetos independientes','predict',contador+'\nContador a = new Contador(1);\nContador b = new Contador(1);\na.aumentar();\nSystem.out.println(a.getValor());\nSystem.out.println(b.getValor());','Predice el valor de a y b.',output(2,1),{choices:['2 y 2','1 y 1','2 y 1'],answer:2,explanation:'Cada new crea un objeto diferente. Cambiar a no modifica el estado de b.'});
add(5,'Dos referencias, un objeto','predict',contador+'\nContador a = new Contador(1);\nContador b = a;\nb.aumentar();\nSystem.out.println(a.getValor());\nSystem.out.println(a == b);','Predice el valor y la comparación de referencias.',output(2,true),{choices:['1 y false','2 y true','2 y false'],answer:1,explanation:'b recibe una copia de la referencia a. Ambas apuntan al mismo objeto. == es true porque la identidad es la misma.'});
add(5,'Crear en lugar de compartir','fix',contador+'\nContador a = new Contador(1);\nContador b = new Contador(1);\nb.aumentar();\nSystem.out.println(a.getValor());\nSystem.out.println(b.getValor());','Haz independientes a y b; imprime 1 y 2.',output(1,2),{starter:contador+'\nContador a = new Contador(1);\nContador b = a;\nb.aumentar();\nSystem.out.println(a.getValor());\nSystem.out.println(b.getValor());',hint:'Copiar una referencia no clona el objeto. Usa otro new.'});
add(5,'Composición: una misión tiene un robot','order','class Equipo {\n  Robot miembro;\n  Equipo(Robot miembro) { this.miembro = miembro; }\n  void trabajar() { miembro.este(); }\n}\nEquipo equipo = new Equipo(robot);\nequipo.trabajar();','Usa un Equipo que contiene a Atlas para llegar a (1, 2).',at(1,2),{chunks:['class Equipo {\n  Robot miembro;\n  Equipo(Robot miembro) { this.miembro = miembro; }\n  void trabajar() { miembro.este(); }\n}','Equipo equipo = new Equipo(robot);','equipo.trabajar();'],explanation:'Equipo no es un Robot: tiene una referencia a un Robot. Esa relación se llama composición.'});
add(5,'Tu clase con estado','write','class Contador {\n  int valor;\n  Contador(int inicial) { valor = inicial; }\n  void aumentar() { valor++; }\n  int getValor() { return valor; }\n}\nContador c = new Contador(5);\nc.aumentar();\nc.aumentar();\nSystem.out.println(c.getValor());','Completa Contador: inicia en 5, aumenta dos veces e imprime 7.',all(output(7),field('Contador','valor',7)),{starter:'class Contador {\n  int valor;\n  Contador(int inicial) { /* Inicializa */ }\n  void aumentar() { /* Modifica el atributo */ }\n  int getValor() { return valor; }\n}\nContador c = new Contador(5);\nc.aumentar();\nc.aumentar();\nSystem.out.println(c.getValor());',require:'class Contador'});
add(5,'Los métodos reciben referencias por valor','write','static void mover(Robot r) { r.este(); }\nstatic void reemplazar(Robot r) { r = new Robot("Nuevo"); }\nmover(robot);\nreemplazar(robot);\nSystem.out.println(robot.getNombre());\nSystem.out.println(robot.getX());','Mueve el objeto y comprueba que reasignar el parámetro no reemplaza robot. Imprime Atlas y 1.',all(at(1,2),output('Atlas',1)),{starter:'static void mover(Robot r) { /* Mueve r */ }\nstatic void reemplazar(Robot r) { r = new Robot("Nuevo"); }\nmover(robot);\nreemplazar(robot);\n// Imprime nombre y x de robot.',hint:'El parámetro copia una referencia. Puede modificar el objeto compartido; reasignar r cambia únicamente ese parámetro.'});
add(5,'Proyecto · Dos mensajeros','project','class Mensajero {\n  Robot robot;\n  Mensajero(Robot robot) { this.robot = robot; }\n  void llevar(int pasos) {\n    robot.recoger();\n    for (int i = 0; i < pasos; i++) { robot.este(); }\n    robot.dejar();\n  }\n}\nMensajero primero = new Mensajero(robot);\nMensajero segundo = new Mensajero(ayudante);\nprimero.llevar(2);\nsegundo.llevar(3);','Crea dos Mensajero: Atlas entrega en (2, 2) y Luna en (3, 3).',all(at(2,2),at(3,3,'Luna'),s=>robot(s).delivered===1&&robot(s,'Luna').delivered===1),{starter:'class Mensajero {\n  Robot robot;\n  Mensajero(Robot robot) { this.robot = robot; }\n  void llevar(int pasos) { /* Recoge, viaja y entrega */ }\n}\n// Crea dos mensajeros con robots distintos y llama llevar().',initial:{helper:{},boxes:[[0,2,1],[0,3,1]],targets:[[2,2],[3,3]]},require:'Mensajero'});
// 61–70: encapsulation and dynamic dispatch.
const bateria=`class Bateria {\n  private int energia;\n  Bateria(int energia) { this.energia = energia; }\n  public int getEnergia() { return energia; }\n  public void gastar(int cantidad) {\n    if (cantidad >= 0 && cantidad <= energia) { energia -= cantidad; }\n  }\n}`;
add(6,'El estado se protege','predict',bateria+'\nBateria b = new Bateria(5);\nb.gastar(8);\nSystem.out.println(b.getEnergia());','Predice el estado después de una petición inválida.',output(5),{choices:['-3','0','5'],answer:2,explanation:'El método público valida antes de cambiar el atributo private. Rechaza gastar 8 cuando solo hay 5.'});
add(6,'Leer mediante un método público','fix',bateria+'\nBateria b = new Bateria(5);\nSystem.out.println(b.getEnergia());','Lee la energía respetando private e imprime 5.',output(5),{starter:bateria+'\nBateria b = new Bateria(5);\nSystem.out.println(b.energia);',hint:'Desde jugar() no puedes leer energia directamente. La clase ofrece getEnergia().'});
add(6,'Herencia con comportamiento adicional','order','class Explorador extends Robot {\n  Explorador(String nombre) { super(nombre); }\n  void explorar() { este(); norte(); }\n}\nExplorador e = new Explorador("Eco");\ne.explorar();','El Explorador Eco termina en (1, 2), desde su inicio (0, 3).',at(1,2,'Eco'),{chunks:['class Explorador extends Robot {\n  Explorador(String nombre) { super(nombre); }\n  void explorar() { este(); norte(); }\n}','Explorador e = new Explorador("Eco");','e.explorar();'],hint:'extends permite reutilizar los movimientos de Robot. super(nombre) inicializa el nombre del Robot base.'});
const rutas=`class Ruta {\n  int coste() { return 1; }\n}\nclass RutaRapida extends Ruta {\n  int coste() { return 3; }\n}`;
add(6,'El objeto elige el método','predict',rutas+'\nRuta r = new RutaRapida();\nSystem.out.println(r.coste());','Predice qué implementación de coste() se usa.',output(3),{choices:['1','3','Error por usar Ruta'],answer:1,explanation:'La referencia tiene tipo Ruta, pero el objeto es RutaRapida. Java ejecuta el método sobrescrito del objeto real.'});
add(6,'Un contrato compartido','predict','interface Tarea { void ejecutar(Robot r); }\nclass Avance implements Tarea {\n  public void ejecutar(Robot r) { r.este(); }\n}\nTarea t = new Avance();\nt.ejecutar(robot);','Predice el movimiento a través de Tarea.',at(1,2),{choices:['Atlas termina en (1, 2)','No se puede usar una interfaz como referencia','Se crean dos robots'],explanation:'La interfaz declara el contrato. Avance lo implementa. Una referencia Tarea puede usar esa implementación.'});
add(6,'Implementar exactamente el contrato','fix','interface Tarea { void ejecutar(Robot r); }\nclass Avance implements Tarea {\n  public void ejecutar(Robot r) { r.este(); }\n}\nTarea t = new Avance();\nt.ejecutar(robot);','Implementa ejecutar(Robot r) y mueve Atlas a (1, 2).',at(1,2),{starter:'interface Tarea { void ejecutar(Robot r); }\nclass Avance implements Tarea {\n  public void ejecutar(Robot r) { /* Falta el comportamiento */ }\n}\nTarea t = new Avance();\nt.ejecutar(robot);'});
add(6,'Usar polimorfismo en un método','order',rutas+'\nstatic void imprimirCoste(Ruta r) { System.out.println(r.coste()); }\nRuta normal = new Ruta();\nRuta rapida = new RutaRapida();\nimprimirCoste(normal);\nimprimirCoste(rapida);','El mismo método imprime 1 y 3 según el objeto recibido.',output(1,3),{chunks:[rutas,'static void imprimirCoste(Ruta r) { System.out.println(r.coste()); }','Ruta normal = new Ruta();','Ruta rapida = new RutaRapida();','imprimirCoste(normal);','imprimirCoste(rapida);']});
add(6,'Encapsular un contador','write','class ContadorSeguro {\n  private int valor = 0;\n  public void sumar(int n) { if (n > 0) { valor += n; } }\n  public int getValor() { return valor; }\n}\nContadorSeguro c = new ContadorSeguro();\nc.sumar(3);\nc.sumar(-5);\nSystem.out.println(c.getValor());','Protege valor, acepta 3, rechaza -5 e imprime 3.',all(output(3),field('ContadorSeguro','valor',3)),{starter:'class ContadorSeguro {\n  private int valor = 0;\n  public void sumar(int n) { /* Valida n antes de modificar */ }\n  public int getValor() { return valor; }\n}\nContadorSeguro c = new ContadorSeguro();\nc.sumar(3);\nc.sumar(-5);\nSystem.out.println(c.getValor());'});
add(6,'Sobrescribir sin cambiar la llamada','write','class Ruta { int pasos() { return 1; } }\nclass RutaLarga extends Ruta { int pasos() { return 3; } }\nRuta r = new RutaLarga();\nfor (int i = 0; i < r.pasos(); i++) { robot.este(); }','Sobrescribe pasos(): la misma referencia Ruta lleva Atlas a (3, 2).',at(3,2),{starter:'class Ruta { int pasos() { return 1; } }\nclass RutaLarga extends Ruta { /* Sobrescribe pasos() */ }\nRuta r = new RutaLarga();\nfor (int i = 0; i < r.pasos(); i++) { robot.este(); }',require:'class RutaLarga'});
add(6,'Proyecto · Estrategias intercambiables','project','interface Estrategia { void aplicar(Robot r); }\nclass Recta implements Estrategia {\n  public void aplicar(Robot r) { r.este(); r.este(); }\n}\nclass Desvio implements Estrategia {\n  public void aplicar(Robot r) { r.norte(); r.este(); r.este(); r.sur(); }\n}\nstatic void iniciar(Estrategia e, Robot r) { e.aplicar(r); }\nEstrategia estrategia = new Desvio();\niniciar(estrategia, robot);','Implementa dos estrategias. Usa Desvio para alcanzar (2, 2) alrededor del muro.',at(2,2),{starter:'interface Estrategia { void aplicar(Robot r); }\nclass Recta implements Estrategia {\n  public void aplicar(Robot r) { /* Ruta directa */ }\n}\nclass Desvio implements Estrategia {\n  public void aplicar(Robot r) { /* Rodea el muro */ }\n}\nstatic void iniciar(Estrategia e, Robot r) { e.aplicar(r); }\n// Elige y ejecuta una estrategia.',initial:{walls:[[1,2]],targets:[[2,2]]},require:'new Desvio',hint:'El método iniciar() depende de una interfaz. Cambiar de estrategia no obliga a reescribirlo.'});
// 71–80: collections and object references in collections.
add(7,'El primer índice es cero','predict','int[] datos = new int[]{4, 7, 9};\nSystem.out.println(datos[1]);\nSystem.out.println(datos.length);','Predice elemento y tamaño.',output(7,3),{choices:['4 y 3','7 y 3','7 y 2'],answer:1});
add(7,'Recorrer un arreglo','order','int[] datos = new int[]{2, 3, 4};\nint suma = 0;\nfor (int i = 0; i < datos.length; i++) { suma += datos[i]; }\nSystem.out.println(suma);','Imprime la suma 9.',output(9));
add(7,'No existe el índice length','fix','int[] datos = new int[]{2, 3};\nfor (int i = 0; i < datos.length; i++) { System.out.println(datos[i]); }','Recorre sin salir del arreglo. Imprime 2 y 3.',output(2,3),{starter:'int[] datos = new int[]{2, 3};\nfor (int i = 0; i <= datos.length; i++) { System.out.println(datos[i]); }',hint:'El último índice válido es length - 1. Usa una comparación estricta.'});
add(7,'Un arreglo también es un objeto','predict','int[] a = new int[]{1, 2};\nint[] b = a;\nb[0] = 8;\nSystem.out.println(a[0]);','Predice qué ocurre al compartir el arreglo.',output(8),{choices:['1','8','0'],answer:1,explanation:'a y b apuntan al mismo arreglo. Cambiar b[0] cambia el objeto que también observa a.'});
add(7,'Una lista puede crecer','predict','ArrayList<Integer> pasos = new ArrayList<Integer>();\npasos.add(2);\npasos.add(4);\nSystem.out.println(pasos.size());\nSystem.out.println(pasos.get(1));','Predice tamaño y segundo elemento.',output(2,4),{choices:['2 y 4','2 y 2','4 y 2']});
add(7,'Leer un índice válido de la lista','fix','ArrayList<Integer> datos = new ArrayList<Integer>();\ndatos.add(6);\nSystem.out.println(datos.get(0));','Imprime el primer elemento: 6.',output(6),{starter:'ArrayList<Integer> datos = new ArrayList<Integer>();\ndatos.add(6);\nSystem.out.println(datos.get(1));',hint:'Las listas también comienzan en el índice 0.'});
add(7,'Una flota de objetos','order','Robot[] flota = new Robot[]{robot, ayudante};\nfor (int i = 0; i < flota.length; i++) { flota[i].este(); }\nSystem.out.println(flota.length);','Mueve ambos robots al este e imprime 2.',all(at(1,2),at(1,3,'Luna'),output(2)),{initial:{helper:{}},chunks:['Robot[] flota = new Robot[]{robot, ayudante};','for (int i = 0; i < flota.length; i++) { flota[i].este(); }','System.out.println(flota.length);']});
add(7,'Encontrar un máximo','write','int[] energia = new int[]{3, 8, 5};\nint maximo = energia[0];\nfor (int i = 1; i < energia.length; i++) {\n  if (energia[i] > maximo) { maximo = energia[i]; }\n}\nSystem.out.println(maximo);','Encuentra el máximo del arreglo e imprime 8.',output(8),{starter:'int[] energia = new int[]{3, 8, 5};\nint maximo = energia[0];\n// Recorre y actualiza el máximo.\n',hint:'Compara cada elemento con el mejor visto hasta ahora. No reinicies maximo en cada vuelta.'});
add(7,'Filtrar datos','write','int[] datos = new int[]{1, 4, 2, 5};\nArrayList<Integer> grandes = new ArrayList<Integer>();\nfor (int i = 0; i < datos.length; i++) {\n  if (datos[i] >= 4) { grandes.add(datos[i]); }\n}\nSystem.out.println(grandes.size());\nSystem.out.println(grandes.get(0));\nSystem.out.println(grandes.get(1));','Guarda los valores >= 4 en una lista. Imprime 2, 4 y 5.',output(2,4,5),{starter:'int[] datos = new int[]{1, 4, 2, 5};\nArrayList<Integer> grandes = new ArrayList<Integer>();\n// Filtra y después imprime tamaño y elementos.',require:'grandes.add'});
add(7,'Proyecto · Entregas en lote','project','Robot[] flota = new Robot[]{robot, ayudante};\nint[] pasos = new int[]{2, 3};\nfor (int i = 0; i < flota.length; i++) {\n  flota[i].recoger();\n  for (int j = 0; j < pasos[i]; j++) { flota[i].este(); }\n  flota[i].dejar();\n}','Procesa la flota con arreglos. Atlas entrega en (2, 2) y Luna en (3, 3).',all(at(2,2),at(3,3,'Luna'),s=>robot(s).delivered===1&&robot(s,'Luna').delivered===1),{starter:'Robot[] flota = new Robot[]{robot, ayudante};\nint[] pasos = new int[]{2, 3};\n// Para cada robot: recoger, viajar sus pasos y entregar.',initial:{helper:{},boxes:[[0,2,1],[0,3,1]],targets:[[2,2],[3,3]]},require:'flota[i]'});
// 81–90: varied combined problems and transfer beyond the board.
add(8,'Leer una expedición completa','predict','static int cargar(Robot r) {\n  int total = 0;\n  while (r.hayCaja()) { r.recoger(); total++; }\n  return total;\n}\nint cantidad = cargar(robot);\nfor (int i = 0; i < cantidad; i++) { robot.este(); }\nSystem.out.println(robot.getX());','Predice hasta dónde viaja según el número de cajas.',all(at(3,2),output(3)),{initial:{boxes:[[0,2,3]],targets:[[3,2]]},choices:['1','3','0'],answer:1});
add(8,'Respetar dependencias','order','static void viajar(Robot r, int n) {\n  for (int i = 0; i < n; i++) { r.este(); }\n}\nrobot.recargar();\nrobot.recoger();\nviajar(robot, 4);\nrobot.dejar();','Recarga, recoge y entrega en (4, 2).',all(at(4,2),s=>robot(s).delivered===1),{initial:{robot:{energy:1},boxes:[[0,2,1]],targets:[[4,2]]},chunks:['static void viajar(Robot r, int n) {\n  for (int i = 0; i < n; i++) { r.este(); }\n}','robot.recargar();','robot.recoger();','viajar(robot, 4);','robot.dejar();']});
add(8,'Una variable fuera de alcance','fix','int total = 0;\nfor (int i = 0; i < 3; i++) { total++; }\nSystem.out.println(total);','Cuenta vueltas e imprime 3 con una variable que siga en alcance.',output(3),{starter:'for (int i = 0; i < 3; i++) {\n  int total = i + 1;\n}\nSystem.out.println(total);',hint:'Una variable declarada dentro del bloque deja de existir al salir. Declara el acumulador antes del for.'});
add(8,'Identidad dentro de una flota','predict','Robot[] flota = new Robot[]{robot, robot};\nfor (int i = 0; i < flota.length; i++) { flota[i].este(); }\nSystem.out.println(robot.getX());','Predice cuánto se mueve cuando dos elementos comparten objeto.',all(at(2,2),output(2)),{choices:['1: un movimiento por robot','2: ambas referencias apuntan a Atlas','0: el arreglo copia los robots'],answer:1,explanation:'El arreglo contiene dos referencias al mismo robot. El bucle mueve ese objeto dos veces.'});
add(8,'Polimorfismo en una colección','predict','interface Coste { int valor(); }\nclass Corto implements Coste { public int valor() { return 2; } }\nclass Largo implements Coste { public int valor() { return 5; } }\nCoste[] rutas = new Coste[]{new Corto(), new Largo()};\nint suma = 0;\nfor (int i = 0; i < rutas.length; i++) { suma += rutas[i].valor(); }\nSystem.out.println(suma);','Predice la suma de las implementaciones.',output(7),{choices:['4','10','7'],answer:2});
add(8,'No permitir un saldo negativo','fix','class Cuenta {\n  private int saldo = 10;\n  public void pagar(int coste) {\n    if (coste >= 0 && coste <= saldo) { saldo -= coste; }\n  }\n  public int getSaldo() { return saldo; }\n}\nCuenta c = new Cuenta();\nc.pagar(12);\nc.pagar(3);\nSystem.out.println(c.getSaldo());','Rechaza 12, acepta 3 e imprime saldo 7.',all(output(7),field('Cuenta','saldo',7)),{starter:'class Cuenta {\n  private int saldo = 10;\n  public void pagar(int coste) { saldo -= coste; }\n  public int getSaldo() { return saldo; }\n}\nCuenta c = new Cuenta();\nc.pagar(12);\nc.pagar(3);\nSystem.out.println(c.getSaldo());',hint:'La clase debe mantener su regla: saldo >= 0. Valida el coste antes de modificar el atributo.'});
add(8,'Consola · Contar aprobados','write','int[] notas = new int[]{5, 8, 6, 9};\nint aprobados = 0;\nfor (int i = 0; i < notas.length; i++) {\n  if (notas[i] >= 6) { aprobados++; }\n}\nSystem.out.println("Aprobados: " + aprobados);','Sin mover robots, cuenta notas >= 6 e imprime Aprobados: 3.',output('Aprobados: 3'),{starter:'int[] notas = new int[]{5, 8, 6, 9};\nint aprobados = 0;\n// Recorre, cuenta e imprime.',hint:'Transfiere la misma lógica a datos de consola. Cada nota que cumple la condición aumenta un contador.'});
add(8,'Consola · Un producto con reglas','write','class Producto {\n  private int stock;\n  Producto(int stock) { this.stock = stock; }\n  public boolean vender(int cantidad) {\n    if (cantidad > 0 && cantidad <= stock) {\n      stock -= cantidad;\n      return true;\n    }\n    return false;\n  }\n  public int getStock() { return stock; }\n}\nProducto p = new Producto(5);\nSystem.out.println(p.vender(2));\nSystem.out.println(p.vender(8));\nSystem.out.println(p.getStock());','Implementa vender(): acepta 2, rechaza 8. Imprime true, false y 3.',all(output(true,false,3),field('Producto','stock',3)),{starter:'class Producto {\n  private int stock;\n  Producto(int stock) { this.stock = stock; }\n  public boolean vender(int cantidad) {\n    // Valida, modifica y devuelve el resultado.\n    return false;\n  }\n  public int getStock() { return stock; }\n}\nProducto p = new Producto(5);\nSystem.out.println(p.vender(2));\nSystem.out.println(p.vender(8));\nSystem.out.println(p.getStock());'});
add(8,'Proyecto · Informe de inventario','project','class Producto {\n  private int unidades;\n  Producto(int unidades) { this.unidades = unidades; }\n  public int getUnidades() { return unidades; }\n}\nProducto[] inventario = new Producto[]{new Producto(3), new Producto(0), new Producto(5)};\nint total = 0;\nint agotados = 0;\nfor (int i = 0; i < inventario.length; i++) {\n  total += inventario[i].getUnidades();\n  if (inventario[i].getUnidades() == 0) { agotados++; }\n}\nSystem.out.println("Unidades: " + total);\nSystem.out.println("Agotados: " + agotados);','Modela productos con encapsulación. Imprime Unidades: 8 y Agotados: 1.',output('Unidades: 8','Agotados: 1'),{starter:'class Producto {\n  private int unidades;\n  Producto(int unidades) { this.unidades = unidades; }\n  public int getUnidades() { return unidades; }\n}\nProducto[] inventario = new Producto[]{new Producto(3), new Producto(0), new Producto(5)};\n// Calcula el total y la cantidad de productos agotados.',require:'inventario[i]',hint:'Mantén dos acumuladores independientes: uno suma unidades; el otro cuenta productos sin existencias.'});
add(8,'Proyecto final · Central de reparto','project','interface Ruta { void viajar(Robot r); }\nclass Desvio implements Ruta {\n  public void viajar(Robot r) { r.norte(); r.este(); r.este(); r.sur(); }\n}\nclass Recta implements Ruta {\n  public void viajar(Robot r) { for (int i = 0; i < 3; i++) { r.este(); } }\n}\nclass Servicio {\n  private Robot robot;\n  private Ruta ruta;\n  Servicio(Robot robot, Ruta ruta) { this.robot = robot; this.ruta = ruta; }\n  public void entregar() { robot.recoger(); ruta.viajar(robot); robot.dejar(); }\n}\nServicio[] servicios = new Servicio[]{new Servicio(robot, new Desvio()), new Servicio(ayudante, new Recta())};\nfor (int i = 0; i < servicios.length; i++) { servicios[i].entregar(); }\nSystem.out.println(robot.getEntregas() + ayudante.getEntregas());','Combina interfaces, composición y un arreglo de servicios. Atlas entrega en (2, 2), Luna en (3, 3). Imprime 2.',all(at(2,2),at(3,3,'Luna'),s=>robot(s).delivered===1&&robot(s,'Luna').delivered===1,output(2)),{starter:'interface Ruta { void viajar(Robot r); }\nclass Desvio implements Ruta {\n  public void viajar(Robot r) { /* Rodea el muro */ }\n}\nclass Recta implements Ruta {\n  public void viajar(Robot r) { /* Tres pasos al este */ }\n}\nclass Servicio {\n  private Robot robot;\n  private Ruta ruta;\n  Servicio(Robot robot, Ruta ruta) { this.robot = robot; this.ruta = ruta; }\n  public void entregar() { /* Recoger, viajar y dejar */ }\n}\n// Crea un arreglo de servicios con las dos rutas.\n// Ejecuta cada servicio e imprime el total de entregas.',initial:{helper:{},boxes:[[0,2,1],[0,3,1]],walls:[[1,2]],targets:[[2,2],[3,3]]},require:'Servicio[]',hint:'La ruta sabe cómo viajar; el servicio coordina la entrega. Cada servicio guarda su robot y su estrategia.'});
const orderStart=m=>m.id==='m06'?[...m.chunks.slice(1),m.chunks[0]]:m.chunks.slice().reverse();
globalThis.JavaCourse={chapters,levels,robot,orderStart,grade(m,result,source){return !result.error&&m.check(result.final)&&(!m.require||source.replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g,'').includes(m.require));}};
})();
